### ISSUE TITLE
Service does not start under Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by frne** [atosatto/ansible-minio#20]
Maybe, this is just a question, but I cannot manage to get the role running if provisioning an Ubuntu Xenial Server.

Ansible Playbook (snip):

```yml
- hosts: all
  become: yes
  roles:
    - atosatto.minio
  vars:
    minio_server_datadirs: [ "/data" ]
```

*Note: Mkdir-ed `/data` manually, doesn't make a difference*

Minio service doesn't start. If I try to start it manually using `sudo service minio start` it runs for a short time:
```bash
sudo service minio status
● minio.service - Minio
   Loaded: loaded (/lib/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-07-06 19:34:27 UTC; 3s ago
     Docs: https://docs.minio.io
  Process: 1523 ExecStartPre=/bin/bash -c [ -n "${MINIO_VOLUMES}" ] || echo "Variable MINIO_VOLUMES not set in /etc/default/minio" (code=exited, status=0/SUCCESS)
 Main PID: 1528 (minio)
    Tasks: 7
   Memory: 2.7M
      CPU: 14ms
   CGroup: /system.slice/minio.service
           └─1528 /usr/local/bin/minio server --address :9091 /data

Jul 06 19:34:27 ubuntu-xenial systemd[1]: Starting Minio...
Jul 06 19:34:27 ubuntu-xenial systemd[1]: Started Minio.
```
Then, [http://server.tld:9091](http://server.tld:9091) is called in browser. => Connection refused

When `sudo service minio status` is called after that:

```bash
● minio.service - Minio
   Loaded: loaded (/lib/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-07-06 19:34:32 UTC; 32s ago
     Docs: https://docs.minio.io
  Process: 1528 ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES (code=exited, status=1/FAILURE)
  Process: 1523 ExecStartPre=/bin/bash -c [ -n "${MINIO_VOLUMES}" ] || echo "Variable MINIO_VOLUMES not set in /etc/default/minio" (code=exited, status=0/SUCCESS)
 Main PID: 1528 (code=exited, status=1/FAILURE)

Jul 06 19:34:27 ubuntu-xenial systemd[1]: Starting Minio...
Jul 06 19:34:27 ubuntu-xenial systemd[1]: Started Minio.
Jul 06 19:34:32 ubuntu-xenial minio[1528]: [75B blob data]
Jul 06 19:34:32 ubuntu-xenial minio[1528]: [81B blob data]
Jul 06 19:34:32 ubuntu-xenial systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 19:34:32 ubuntu-xenial systemd[1]: minio.service: Unit entered failed state.
Jul 06 19:34:32 ubuntu-xenial systemd[1]: minio.service: Failed with result 'exit-code'.
```

Am I doing it wrong, or is it a bug in the recipe / minio?

**Comment by frne** [comment]
When `/data` is chemod-ed with `777`, it works. Would be an improvement to the role, if the data directories are created and privileged correctly by the role, so they work. But besides that, this is basially **resolved**.

**Comment by atosatto** [comment]
Hi @frne, yes indeed it looks like a permissions problem. Are you using the latest version of the role (`master`)?

**Comment by frne** [comment]
@atosatto installed via ansible galaxy yesterday. Will checkout master and try again.

**Comment by atosatto** [comment]
Hi @frne I can confirm that with master it does work.
We will be doing soon a new release to avoid you to have to depend on master.
Can you confirm that master is working also for you?

**Comment by frne** [comment]
@atosatto Yes, everything fine on master. Thx for your work.
