### ISSUE TITLE
Fails to run from master branch

### ISSUE THREAD

**Issue by johnrobertporter** [atosatto/ansible-minio#22]
```
TASK [ansible-minio : Compose Minio download url] ******************************
ok: [vagrant]

TASK [ansible-minio : Minio server checksum for amd64 architecture] ************
objc[89476]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[89476]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

I have no idea about how this stuff works, but this is the error I get when trying to run the master branch.

I wanted to make use of the `minio_server_make_datadirs` var as this always fails to start the service otherwise.

**Comment by atosatto** [comment]
Hi @johnrobertporter, thanks for reporting this issue.
Can you please provide us some more information on the target OS and on how you are using the role?

**Comment by johnrobertporter** [comment]
Hiya,

The OS is Ubuntu 16.04 (provided by Bento for vagrant). The previous version runs fine but never creates the directories so fails to start. This one seems unable to process this task without hanging. It doesn't give an error back to ansible either, so I didn't notice it for ages the first time.

Anyhoo, I use it in a vagrant setup; vagrant pulls and starts the box, then ansible provisions it. No other issues apart from this checksum one.

Latest version of vagrant and ansible (I'm on another machine so can't see exact numbers).

**Comment by atosatto** [comment]
Can you please try with the latest master release and provide us the output of the following commands `ansible --version`?

**Comment by johnrobertporter** [comment]
Hi, sorry fr the delay, I've been on holiday :)

Running from the latest master branch:

```
TASK [ansible-minio : Get the Minio server checksum for amd64 architecture] ****
objc[7376]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[7376]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

```
$ ansible --version
ansible 2.6.3
  config file = /Volumes/Projects/thoughtriver/ansible/client-database/ansible.cfg
  configured module search path = [u'/Users/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

Hope this is helpful

**Comment by johnrobertporter** [comment]
Ah, ok, this is not your issue, it's Python on MacOS X:

https://github.com/ansible/ansible/issues/34056

Sorry to bother you with it :)

**Comment by atosatto** [comment]
No problem! Good to know what the issue was in the end :)
