### ISSUE TITLE
Suggestion to allow disable create/update the default user/group running minio and, if is created by this role, set `create_home: no`

### ISSUE THREAD

**Issue by fititnt** [atosatto/ansible-minio#43]
- Refs #15
- Refs https://github.com/atosatto/ansible-minio/issues/15#issuecomment-399982774
- https://docs.ansible.com/ansible/latest/modules/user_module.html, parameter `create_home: (default) yes`
- Refs this file

https://github.com/atosatto/ansible-minio/blob/15ad3a3604f658dbbe30e593d4c148983af60320/tasks/install-server.yml#L25-L30

The PR #41 by @drakmail did not explicitly removed the default ansible behavior of not create the home. 

### Suggestion to add by default `create_home: no`

On this case, I agree with @SuperQ to not create home if the user is created by `atosatto.ansible-minio`. The way to implement this would be add an extra line  `create_home: no`.

### Suggestion to allow not manange user/group running minio

The problem with this is that, different from the option to not allow this role create the data dirs with `minio_server_make_datadirs: true` there is no option to disable management of the user/group. So even if a user define another user/group to run minio, this role may in fact revert options of user created by other roles or tasks.

**Comment by atosatto** [comment]
Hi @fititnt, this sounds like a good idea indeed.
Any chance for you to contribute this in a PR? I will review it and merge it as soon as possible.

**Comment by fititnt** [comment]
@atosatto Sounds like a plan.

It's an easy addition, but I will do some basic tests.
